export enum ContentCategories {
  MS = 'М/с',
  EDUCATIONAL = 'Познавательное',
  LEISURE = 'Досуг, хобби',
  COMEDY = 'Юмор',
  CARTOON = 'М/ф',
  NEWS = 'Новости',
  FILM = 'Фильмы',
  SERIAL = 'Сериалы',
  ANIME = 'Аниме',
  DOCUMENTARY = 'Документальные',
  MUSIC = 'Музыка',
  TV_SHOW = 'ТВ-шоу',
  SHOW = 'Шоу',
}
